
["Roost Ultimate Spawn Control"]
	#Enable/Disable Spawning
	"Enable Spawning" = true
	"Enable String Chicken Spawning" = true
	"Enable Spruce Chicken Spawning" = true
	"Enable Sweetberries Chicken Spawning" = true
	"Enable Sugar Chicken Spawning" = true
	"Enable Sponge Chicken Spawning" = true
	"Enable Spider Eye Chicken Spawning" = true
	"Enable Snow Chicken Spawning" = true
	"Enable Sand Chicken Spawning" = true
	"Enable Rotten Chicken Spawning" = true
	"Enable Rabbithide Chicken Spawning" = true
	"Enable Oak Chicken Spawning" = true
	"Enable Netherrack Chicken Spawning" = true
	"Enable Melon Chicken Spawning" = true
	"Enable Leather Chicken Spawning" = true
	"Enable Jungle Chicken Spawning" = true
	"Enable Acacia Chicken Spawning" = true
	"Enable Apple Chicken Spawning" = true
	"Enable Beetroot Chicken Spawning" = true
	"Enable Birch Chicken Spawning" = true
	"Enable Carrot Chicken Spawning" = true
	"Enable Honeycomb Chicken Spawning" = true
	"Enable Glow Berries Chicken Spawning" = true
	"Enable Dark Oak Chicken Spawning" = true
	"Enable Cobble Chicken Spawning" = true
	"Enable Stone Chicken Spawning" = true
	"Enable Wool Chicken Spawning" = true
	#Set Spawnweights
	"String Spawnweight" = 5
	"Spruce Spawnweight" = 20
	"Sweetberries Spawnweight" = 8
	"Sugar Spawnweight" = 20
	"Sponge Spawnweight" = 8
	"Spider Eye Spawnweight" = 10
	"Snow Spawnweight" = 8
	"Sand Spawnweight" = 20
	"Rotten Spawnweight" = 8
	"Rabbit Hide Spawnweight" = 8
	"Oak Spawnweight" = 20
	"Netherrack Spawnweight" = 40
	"Melon Spawnweight" = 8
	"Leather Spawnweight" = 8
	"Jungle Spawnweight" = 20
	"Acacia Spawnweight" = 20
	"Apple Spawnweight" = 8
	"Beetroot Spawnweight" = 8
	"Birch Spawnweight" = 20
	"Carrot Spawnweight" = 8
	"Honeycomb Spawnweight" = 8
	"Glowberries Spawnweight" = 0
	"Dark Oak Spawnweight" = 20
	"Cobble Spawnweight" = 15
	"Stone Spawnweight" = 8
	#Set MinGroupsizes
	"String MinGroupsize" = 1
	"Spruce MinGroupsize" = 1
	"Sweetberries MinGroupsize" = 1
	"Sugar MinGroupsize" = 1
	"Sponge MinGroupsize" = 1
	"Spider Eye MinGroupsize" = 1
	"Snow MinGroupsize" = 1
	"Sand MinGroupsize" = 1
	"Rotten MinGroupsize" = 1
	"Rabbit Hide MinGroupsize" = 1
	"Oak MinGroupsize" = 1
	"Netherrack MinGroupsize" = 1
	"Melon MinGroupsize" = 1
	"Leather MinGroupsize" = 1
	"Jungle MinGroupsize" = 1
	"Acacia MinGroupsize" = 1
	"Apple MinGroupsize" = 1
	"Beetroot MinGroupsize" = 1
	"Birch MinGroupsize" = 1
	"Carrot MinGroupsize" = 1
	"Honeycomb MinGroupsize" = 1
	"Glowberries MinGroupsize" = 1
	"Dark Oak MinGroupsize" = 1
	"Cobble MinGroupsize" = 1
	#Set MaxGroupsizes
	"String MaxGroupsize" = 2
	"Spruce MaxGroupsize" = 2
	"Sweetberries MaxGroupsize" = 2
	"Sugar MaxGroupsize" = 2
	"Sponge MaxGroupsize" = 2
	"Spider Eye MaxGroupsize" = 2
	"Snow MaxGroupsize" = 2
	"Sand MaxGroupsize" = 2
	"Rotten MaxGroupsize" = 2
	"Rabbit Hide MaxGroupsize" = 2
	"Oak MaxGroupsize" = 2
	"Netherrack MaxGroupsize" = 2
	"Melon MaxGroupsize" = 2
	"Leather MaxGroupsize" = 2
	"Jungle MaxGroupsize" = 2
	"Acacia MaxGroupsize" = 2
	"Apple MaxGroupsize" = 2
	"Beetroot MaxGroupsize" = 2
	"Birch MaxGroupsize" = 2
	"Carrot MaxGroupsize" = 2
	"Honeycomb MaxGroupsize" = 2
	"Glowberries MaxGroupsize" = 2
	"Dark Oak MaxGroupsize" = 2
	"Cobble MaxGroupsize" = 2

